<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRfqxzLM\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRfqxzLM/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerRfqxzLM.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerRfqxzLM\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerRfqxzLM\appAppKernelProdContainer([
    'container.build_hash' => 'RfqxzLM',
    'container.build_id' => '31840a75',
    'container.build_time' => 1758376161,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRfqxzLM');
